### ISSUE TITLE
Error: failed to commit transaction (conflicting files)

### ISSUE THREAD

**Issue by Rahtgaz** [Antergos/antergos-packages#241]
Copy/paste, from original error report on the official forums: https://forum.antergos.com/topic/8039/error-failed-to-commit-transaction-conflicting-files

> 
> I went to update Antergos using the terminal and Pamac same error
> 
> I type
> `sudo pacman -Syyu`
> 
> I got
> ```
> :: Starting full system upgrade…
> :: Replace antergos-desktop with antergos/antergos-gnome-setup? [Y/n]
> :: Replace antergos-desktop with antergos/antergos-openbox-setup? [Y/n]
> :: Replace antergos-gsettings with antergos/antergos-gnome-setup? [Y/n]
> :: Replace antergos-gsettings with antergos/antergos-openbox-setup? [Y/n]
> ```
> 
> I hit `Y` to replace all
> 
> Here is the packages
> ```
> Packages (25) antergos-desktop-0.7-1 [removal] antergos-gnome-setup-1.0-3
> antergos-gsettings-1.3-3 [removal] antergos-openbox-setup-1.0-1
> bamf-0.5.3-1 compton-0.1_beta2.5-8 intltool-0.51.0-3
> libconfig-1.6-2 libfm-extra-1.2.5-1 libwnck3-3.24.1-1
> libxres-1.0.7-1 lxmenu-data-0.1.5-1 menu-cache-1.0.2-2
> obkey-1.0-4 oblogout-0.2-18 openbox-3.6.1-3
> openbox-menu-0.8.0-1 pamac-6.0.3-1 perl-xml-parser-2.44-6
> plank-0.11.4-1 plank-theme-numix-0.1-1 python2-dbus-1.2.4-2
> python2-distutils-extra-2.39-2 python2-olefile-0.44-1
> python2-pillow-4.3.0-1
> ```
> 
> Here is the error:
> ```
> error: failed to commit transaction (conflicting files)
> /etc/oblogout.conf exists in both ‘oblogout’ and 'antergos-openbox-setup’
> antergos-openbox-setup: /etc/skel/.config/qt5ct/qt5ct.conf exists in filesystem
> Errors occurred, no packages were upgraded.
> ```
> 
> The desktop I install is Gnome and it’s a fresh install

**Comment by Rahtgaz** [comment]
I can confirm this issue on my own system
```
[2619][7] [0][~] $ sudo pacman -Syu
:: Synchronizing package databases...
 antergos is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 sublime-text is up to date
:: Starting full system upgrade...
:: Replace antergos-gsettings with antergos/antergos-gnome-setup? [Y/n] n
:: Replace antergos-gsettings with antergos/antergos-openbox-setup? [Y/n] n
```

I don' even have openbox or gnome installed on my system. Responding `Yes` to the prompt will generate conflicting errors. Safe method is to answer `No` for the time being.

**Comment by TristanMarion** [comment]
I have the same problem, I'll try to figure it out and tell you if I find something

**Comment by wrighterase** [comment]
had the same issue.  i just refreshed the databases in pamac and then the updates went thru fine.

**Comment by eliezerjuda** [comment]
I have the same problem.... what is the fix?

└──╼ #sudo pacman -Syyu
:: Sincronizando las bases de datos de los paquetes...
 antergos                 163.5 KiB   485K/s 00:00 [######################] 100%
 core                     125.5 KiB   697K/s 00:00 [######################] 100%
 extra                   1657.5 KiB  1298K/s 00:01 [######################] 100%
 community                  4.0 MiB  1063K/s 00:04 [######################] 100%
 multilib                 173.8 KiB   548K/s 00:00 [######################] 100%
:: Iniciando actualización completa del sistema...
:: ¿Remplazar antergos-desktop con antergos/antergos-gnome-setup?  [S/n] n
:: ¿Remplazar antergos-gsettings con antergos/antergos-gnome-setup?  [S/n] n
...el sistema ya está actualizado.

**Comment by karasu** [comment]
This should be fixed by now. Can you guys try a `sudo pacman -Syu` again? Thanks!

**Comment by zdykstra** [comment]
```
Removing antergos-gsettings (1.3-3)...
Installing antergos-gnome-setup (1.0-3)...

```

Looks good here on an XFCE Antergos setup.

**Comment by lukaszjurczak** [comment]
It seems to be fixed.

**Comment by aliencoder16** [comment]
Unfortunately it's not fixed on my end xfce install
:: Synchronizing package databases...
 antergos is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib                 173.8 KiB   949K/s 00:00 [######################] 100%
:: Starting full system upgrade...
:: Replace antergos-desktop with antergos/antergos-gnome-setup? [Y/n] y
:: Replace antergos-gsettings with antergos/antergos-gnome-setup? [Y/n] y
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: antergos-xfce-setup: removing antergos-desktop breaks dependency 'antergos-desktop'

**Comment by Silverbeard00** [comment]
:: Synchronizing package databases...
 antergos                 163.5 KiB   266K/s 00:01 [######################] 100%
 core                     125.5 KiB   392K/s 00:00 [######################] 100%
 extra                   1658.1 KiB  1247K/s 00:01 [######################] 100%
 community                  4.0 MiB  2.79M/s 00:01 [######################] 100%
 multilib                 173.8 KiB  17.0M/s 00:00 [######################] 100%
:: Starting full system upgrade...
:: Replace antergos-desktop with antergos/antergos-gnome-setup? [Y/n] n
:: Replace antergos-gsettings with antergos/antergos-gnome-setup? [Y/n] n
resolving dependencies...
looking for conflicting packages...

Packages (15) antergos-openbox-setup-1.0-3  curl-7.56.0-1
              imagemagick-6.9.9.18-1  krb5-1.15.2-1  lib32-curl-7.56.0-1
              lib32-libcurl-compat-7.56.0-1  libclc-0.2.0+374+0c31bd5-1
              libcurl-compat-7.56.0-1  libinput-1.8.3-1
              networkmanager-openvpn-1.8.1dev+9+gf9e2fd5-1
              python-asn1crypto-0.23.0-1  python-pillow-4.3.0-1
              python2-pillow-4.3.0-1  udiskie-1.7.1-1  youtube-dl-2017.10.01-1

Total Download Size:    0.02 MiB
Total Installed Size:  81.97 MiB
Net Upgrade Size:       0.32 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'antergos-openbox-setup-1.0-3-any.pkg.tar.xz' from mirror.host.ag : Maximum file size exceeded


I'm getting this on my install with openbox.  It tries all the mirrors but says the same thing, and it doesn't matter if I say yes or no to antergos-gnome-setup.

Haven't been able to update for a few days now.  I just tried clearing out the pacman cache but no dice.

**Comment by aliencoder16** [comment]
Bump.. any ideas, or workarounds?

**Comment by aliencoder16** [comment]
Something was done, my updates ran fine.  Thanks

**Comment by alcomposer** [comment]
Did a `$pacman -Syu` and got a similar error today. Was a clean install and all uptodate yesterday. Using Gnome.

```
:: Starting full system upgrade...

Packages (6) antergos-desktop-settings-1.2-2  gnome-settings-daemon-3.26.2-1
             gnome-shell-3.26.2-1  gnome-shell-extensions-3.26.2-1
             krita-3.3.2.1-1  mutter-3.26.2-1

Total Installed Size:  142.29 MiB
Net Upgrade Size:        0.11 MiB

:: Proceed with installation? [Y/n] y

error: failed to commit transaction (conflicting files)
antergos-desktop-settings: /etc/skel/.bashrc exists in filesystem
antergos-desktop-settings: /etc/skel/.config/fontconfig/fonts.conf exists in filesystem
Errors occurred, no packages were upgraded.
```

**Comment by karasu** [comment]
Hi,
@alcomposer 

We're changing how skel files are installed. First there were installed by Cnchi (that was not ok), then there were managed by different packages (was painfully wrong) and now we're trying to setup all of them from the antergos-desktop-settings package.

The best way to handle this in an installed system is just:
`sudo pacman -S antergos-desktop-settings --force`

Sorry for the inconvenience.

Cheers!

**Comment by alcomposer** [comment]
Totally fine @karasu!  Thanks for writing back.  I read another forum (linked from here) and saw the usage of --force.  Considering that it was bashrc and fonts.conf I saw no real danger in using the force. (At least this time)
